[project]
name = "disocrd-siri"
version = "1.1.0"
description = "Discord Siri Bot"
authors = [{ name = "CBite07" }]
requires-python = ">=3.8"
dependencies = [
    "discord.py>=2.3.0",
    "python-dotenv>=1.0.0",
    "aiosqlite>=0.19.0",
    "PyNaCl>=1.5.0"
]

[tool.uv]
# uv 관련 설정(필요시)
